### PR TITLE
Fixed issue #9

### PR DESCRIPTION
**Pull request by FlamptX**
Fixed bot commands not working when replacing prefix with mention.

### CODE REVIEW

**Comment by nerdguyahmad** [comment]
@FlamptX Did you test the changes? If you didn't let me know so I can test it first because even I said in server that this works, I kinda doubt my words.

**Comment by FlamptX** [comment]
> @FlamptX Did you test the changes? If you didn't let me know so I can test it first because even I said in server that this works, I kinda doubt my words.

I didn'r test it 😕 since I had to go somewhere.

**Comment by nerdguyahmad** [comment]
> > @FlamptX Did you test the changes? If you didn't let me know so I can test it first because even I said in server that this works, I kinda doubt my words.
> 
> I didn't test it  since I had to go somewhere.

No problem, I'll test :ok_hand:

**Comment by nerdguyahmad** [comment]
peekaboo

**Pull request merged**
