### PR TITLE
Hello!

### PR DESCRIPTION
**Pull request by LuisPavelA**

### CODE REVIEW

**Comment by nerdguyahmad** [comment]
Pog

**Comment by FlamptX** [comment]
I doubt that people will view this website on an apple touch :/

**Comment by LuisPavelA** [comment]
> I doubt that people will view this website on an apple touch :/

**It is needed :/**

**Comment by FlamptX** [comment]
Why

**Comment by LuisPavelA** [comment]
**_Accessibility_**

**Comment by LuisPavelA** [comment]
**_Oh sorry that I added 1 line of code that probably helps some users_**

**Comment by FlamptX** [comment]
> **_Oh sorry that I added 1 line of code that probably helps some users_**

It doesn't help a single person on Earth

**Comment by LuisPavelA** [comment]
How do you know?

> > **_Oh sorry that I added 1 line of code that probably helps some users_**
> 
> It doesn't help a single person on Earth

**Comment by FlamptX** [comment]
> How do you know?
> 
> > > **_Oh sorry that I added 1 line of code that probably helps some users_**
> > 
> > 
> > It doesn't help a single person on Earth

Common sense

**Comment by nerdguyahmad** [comment]
This is getting out of hand bruh calm @FlamptX adding or removing one line doesnt make a difference. im archiving this now

**Pull request merged**
